# 问题描述

5*5格子，随机1格 为bot出生点、1格为电池、5格为奖励积分。bot 能量上限为5，初始为5，每走1步消耗1能量，电池增加3能量。能量耗尽游戏结束。游戏目标是获取尽可能多的积分。

状态描述：5*5格子，剩余能量

In [1]:
import numpy as np

In [32]:
# 5*5*6
NROW, NCOL, NCHANNEL = 5, 5, 6
INITIAL_ENERGY = 5
def make_state():
    state = np.zeros((5,5,6))
    cells = np.zeros(7, int)
    cells = np.random.choice(NROW*NCOL, size=7, replace=False)
    xs = cells // 5
    ys = cells % 5
    state[xs[0], ys[0], 0] = 1  # 出生点
    state[xs[1], ys[1], 1] = 1  # 电池
    for reward in np.arange(2, 7):  # 奖励
        state[xs[reward], ys[reward], 2] = 1
    set_state_energy(state, INITIAL_ENERGY)
    return cells, xs, ys, state

In [36]:
cells, xs, ys, states = make_state()
cells, xs, ys, states[:,:,1]

(array([13,  5,  7, 17, 19, 12, 24], dtype=int32),
 array([2, 1, 1, 3, 3, 2, 4], dtype=int32),
 array([3, 0, 2, 2, 4, 2, 4], dtype=int32),
 array([[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [24]:
states[0]

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])